"""React 菜单 seed 数据（快照）。

说明:
- 用于 backend-python 的 /menu（slash-admin React）动态路由。
- 与 Vue3 的 sys_menu（/system/*）逻辑解耦；此处仅存 React 所需字段。
- 该快照最初来源于 pc-admin-react/src/_mock/assets_backup.ts 的 DB_MENU。
"""

from __future__ import annotations

REACT_MENU_FLAT: list[dict] = [
    {
        "id": "workbench",
        "parentId": "",
        "name": "sys.nav.workbench",
        "code": "workbench",
        "icon": "local:ic-workbench",
        "type": 2,
        "path": "/workbench",
        "component": "/pages/dashboard/workbench",
    },
    {
        "id": "management",
        "parentId": "",
        "name": "sys.nav.management",
        "code": "management",
        "icon": "local:ic-management",
        "type": 1,
        "path": "/management",
        "component": "",
    },
    {
        "id": "management_system_user",
        "parentId": "management",
        "name": "sys.nav.system.user",
        "code": "management:system:user",
        "icon": None,
        "type": 2,
        "path": "/management/system/user",
        "component": "/pages/management/system/user",
    },
    # 用户管理 - 按钮权限（type=3）
    {
        "id": "management_system_user_btn_create",
        "parentId": "management_system_user",
        "name": "新增",
        "code": "system:user:create",
        "icon": None,
        "type": 3,
    },
    {
        "id": "management_system_user_btn_import",
        "parentId": "management_system_user",
        "name": "导入",
        "code": "system:user:import",
        "icon": None,
        "type": 3,
    },
    {
        "id": "management_system_user_btn_export",
        "parentId": "management_system_user",
        "name": "导出",
        "code": "system:user:export",
        "icon": None,
        "type": 3,
    },
    {
        "id": "management_system_user_btn_get",
        "parentId": "management_system_user",
        "name": "详情",
        "code": "system:user:get",
        "icon": None,
        "type": 3,
    },
    {
        "id": "management_system_user_btn_update",
        "parentId": "management_system_user",
        "name": "修改",
        "code": "system:user:update",
        "icon": None,
        "type": 3,
    },
    {
        "id": "management_system_user_btn_delete",
        "parentId": "management_system_user",
        "name": "删除",
        "code": "system:user:delete",
        "icon": None,
        "type": 3,
    },
    {
        "id": "management_system_user_btn_reset_pwd",
        "parentId": "management_system_user",
        "name": "重置密码",
        "code": "system:user:resetPwd",
        "icon": None,
        "type": 3,
    },
    {
        "id": "management_system_user_btn_update_role",
        "parentId": "management_system_user",
        "name": "分配角色",
        "code": "system:user:updateRole",
        "icon": None,
        "type": 3,
    },
    {
        "id": "management_system_role",
        "parentId": "management",
        "name": "sys.nav.system.role",
        "code": "management:system:role",
        "icon": None,
        "type": 2,
        "path": "/management/system/role",
        "component": "/pages/management/system/role",
    },
    # 角色管理 - 按钮权限（type=3）
    {
        "id": "management_system_role_btn_create",
        "parentId": "management_system_role",
        "name": "新增",
        "code": "system:role:create",
        "icon": None,
        "type": 3,
    },
    {
        "id": "management_system_role_btn_update",
        "parentId": "management_system_role",
        "name": "编辑",
        "code": "system:role:update",
        "icon": None,
        "type": 3,
    },
    {
        "id": "management_system_role_btn_delete",
        "parentId": "management_system_role",
        "name": "删除",
        "code": "system:role:delete",
        "icon": None,
        "type": 3,
    },
    {
        "id": "management_system_role_btn_update_permission",
        "parentId": "management_system_role",
        "name": "保存权限",
        "code": "system:role:updatePermission",
        "icon": None,
        "type": 3,
    },
    {
        "id": "management_system_role_btn_assign",
        "parentId": "management_system_role",
        "name": "分配用户",
        "code": "system:role:assign",
        "icon": None,
        "type": 3,
    },
    {
        "id": "management_system_role_btn_unassign",
        "parentId": "management_system_role",
        "name": "取消分配",
        "code": "system:role:unassign",
        "icon": None,
        "type": 3,
    },
    {
        "id": "management_system_menu",
        "parentId": "management",
        "name": "sys.nav.system.menu",
        "code": "system:menu:list",
        "icon": None,
        "type": 2,
        "path": "/management/system/menu",
        "component": "/pages/management/system/menu",
    },
    # 菜单管理 - 按钮权限（type=3）
    {
        "id": "management_system_menu_btn_create",
        "parentId": "management_system_menu",
        "name": "新增",
        "code": "system:menu:create",
        "icon": None,
        "type": 3,
    },
    {
        "id": "management_system_menu_btn_update",
        "parentId": "management_system_menu",
        "name": "编辑",
        "code": "system:menu:update",
        "icon": None,
        "type": 3,
    },
    {
        "id": "management_system_menu_btn_delete",
        "parentId": "management_system_menu",
        "name": "删除",
        "code": "system:menu:delete",
        "icon": None,
        "type": 3,
    },
    {
        "id": "management_system_menu_btn_clear_cache",
        "parentId": "management_system_menu",
        "name": "清缓存",
        "code": "system:menu:clearCache",
        "icon": None,
        "type": 3,
    },
    {
        "id": "management_system_dept",
        "parentId": "management",
        "name": "sys.nav.system.dept",
        "code": "system:dept:list",
        "icon": None,
        "type": 2,
        "path": "/management/system/dept",
        "component": "/pages/management/system/dept",
    },
    {
        "id": "management_system_file",
        "parentId": "management",
        "name": "sys.nav.system.file",
        "code": "system:file:list",
        "icon": None,
        "type": 2,
        "path": "/management/system/file",
        "component": "/pages/management/system/file",
    },
    {
        "id": "management_system_dict",
        "parentId": "management",
        "name": "sys.nav.system.dict",
        "code": "system:dict:list",
        "icon": None,
        "type": 2,
        "path": "/management/system/dict",
        "component": "/pages/management/system/dict",
    },
    {
        "id": "management_system_option",
        "parentId": "management",
        "name": "sys.nav.system.option",
        "code": "system:siteConfig:get",
        "icon": None,
        "type": 2,
        "path": "/management/system/option",
        "component": "/pages/management/system/option",
    },
    {
        "id": "management_monitor",
        "parentId": "",
        "name": "sys.nav.monitor.index",
        "code": "management:monitor",
        "icon": "solar:monitor-smartphone-bold-duotone",
        "type": 1,
        "path": "/monitor",
        "component": "",
    },
    {
        "id": "management_monitor_online",
        "parentId": "management_monitor",
        "name": "sys.nav.monitor.online",
        "code": "monitor:online:list",
        "icon": None,
        "type": 2,
        "path": "/monitor/online",
        "component": "/pages/management/monitor/online",
    },
    {
        "id": "management_monitor_log",
        "parentId": "management_monitor",
        "name": "sys.nav.monitor.log",
        "code": "monitor:log:list",
        "icon": None,
        "type": 2,
        "path": "/monitor/log",
        "component": "/pages/management/monitor/log",
    },
    {
        "id": "error",
        "parentId": "",
        "name": "sys.nav.error.index",
        "code": "error",
        "icon": "bxs:error-alt",
        "type": 1,
        "path": "/error",
        "component": "",
    },
    {
        "id": "error_403",
        "parentId": "error",
        "name": "sys.nav.error.403",
        "code": "error:403",
        "icon": None,
        "type": 2,
        "path": "/error/403",
        "component": "/pages/sys/error/Page403",
    },
    {
        "id": "error_404",
        "parentId": "error",
        "name": "sys.nav.error.404",
        "code": "error:404",
        "icon": None,
        "type": 2,
        "path": "/error/404",
        "component": "/pages/sys/error/Page404",
    },
    {
        "id": "error_500",
        "parentId": "error",
        "name": "sys.nav.error.500",
        "code": "error:500",
        "icon": None,
        "type": 2,
        "path": "/error/500",
        "component": "/pages/sys/error/Page500",
    },
]
