"""React 菜单 seed 数据（快照）。

说明:
- 用于 backend-python 的 /menu（slash-admin React）动态路由。
- 与 Vue3 的 sys_menu（/system/*）逻辑解耦；此处仅存 React 所需字段。
- 该快照最初来源于 pc-admin-react/src/_mock/assets_backup.ts 的 DB_MENU。
"""

from __future__ import annotations

REACT_MENU_FLAT: list[dict] = [
    {
        "id": "group_dashboard",
        "parentId": "",
        "name": "sys.nav.dashboard",
        "code": "dashboard",
        "icon": None,
        "type": 0,
        "path": "",
        "component": "",
    },
    {
        "id": "group_pages",
        "parentId": "",
        "name": "sys.nav.pages",
        "code": "pages",
        "icon": None,
        "type": 0,
        "path": "",
        "component": "",
    },
    {
        "id": "workbench",
        "parentId": "group_dashboard",
        "name": "sys.nav.workbench",
        "code": "workbench",
        "icon": "local:ic-workbench",
        "type": 2,
        "path": "/workbench",
        "component": "/pages/dashboard/workbench",
    },
    {
        "id": "analysis",
        "parentId": "group_dashboard",
        "name": "sys.nav.analysis",
        "code": "analysis",
        "icon": "local:ic-analysis",
        "type": 2,
        "path": "/analysis",
        "component": "/pages/dashboard/analysis",
    },
    {
        "id": "management",
        "parentId": "group_pages",
        "name": "sys.nav.management",
        "code": "management",
        "icon": "local:ic-management",
        "type": 1,
        "path": "/management",
        "component": "",
    },
    {
        "id": "management_system_user",
        "parentId": "management",
        "name": "sys.nav.system.user",
        "code": "management:system:user",
        "icon": None,
        "type": 2,
        "path": "/management/system/user",
        "component": "/pages/management/system/user",
    },
    {
        "id": "management_system_role",
        "parentId": "management",
        "name": "sys.nav.system.role",
        "code": "management:system:role",
        "icon": None,
        "type": 2,
        "path": "/management/system/role",
        "component": "/pages/management/system/role",
    },
    {
        "id": "management_system_menu",
        "parentId": "management",
        "name": "sys.nav.system.menu",
        "code": "system:menu:list",
        "icon": None,
        "type": 2,
        "path": "/management/system/menu",
        "component": "/pages/management/system/menu",
    },
    {
        "id": "management_system_dept",
        "parentId": "management",
        "name": "sys.nav.system.dept",
        "code": "system:dept:list",
        "icon": None,
        "type": 2,
        "path": "/management/system/dept",
        "component": "/pages/management/system/dept",
    },
    {
        "id": "management_system_file",
        "parentId": "management",
        "name": "sys.nav.system.file",
        "code": "system:file:list",
        "icon": None,
        "type": 2,
        "path": "/management/system/file",
        "component": "/pages/management/system/file",
    },
    {
        "id": "management_system_dict",
        "parentId": "management",
        "name": "sys.nav.system.dict",
        "code": "system:dict:list",
        "icon": None,
        "type": 2,
        "path": "/management/system/dict",
        "component": "/pages/management/system/dict",
    },
    {
        "id": "management_system_option",
        "parentId": "management",
        "name": "sys.nav.system.option",
        "code": "system:siteConfig:get",
        "icon": None,
        "type": 2,
        "path": "/management/system/option",
        "component": "/pages/management/system/option",
    },
    {
        "id": "error",
        "parentId": "group_pages",
        "name": "sys.nav.error.index",
        "code": "error",
        "icon": "bxs:error-alt",
        "type": 1,
        "path": "/error",
        "component": "",
    },
    {
        "id": "error_403",
        "parentId": "error",
        "name": "sys.nav.error.403",
        "code": "error:403",
        "icon": None,
        "type": 2,
        "path": "/error/403",
        "component": "/pages/sys/error/Page403",
    },
    {
        "id": "error_404",
        "parentId": "error",
        "name": "sys.nav.error.404",
        "code": "error:404",
        "icon": None,
        "type": 2,
        "path": "/error/404",
        "component": "/pages/sys/error/Page404",
    },
    {
        "id": "error_500",
        "parentId": "error",
        "name": "sys.nav.error.500",
        "code": "error:500",
        "icon": None,
        "type": 2,
        "path": "/error/500",
        "component": "/pages/sys/error/Page500",
    },
]
